permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 曹井琛
  email: 42629624@qq.com
  link: http://jnchen.me
  weibo: http://weibo.com/caojingchen
  github: http://github.com/jnchen

# 站点信息
title: JnChen's Blog 
description: 一个代码狗的博客
url: http://jnchen.me
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://jnchen.me/images/avatar.png
favicon: http://jnchen.me/images/favicon.ico

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: 

# baidu analytics 设置
analytics :
    provider : custom
    
# disqus 设置
disqus:
  shortname: jnchen
